version: '3'
networks:
  cassandra-cluster:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
services:
  cassandra:
    image: cassandra:4.0.4
    hostname: cassandra
    networks:
      cassandra-cluster:
        ipv4_address: 172.30.0.2
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9142
    ports:
      - 9042:9042
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_LISTEN_ADDRESS=172.30.0.2
      - CASSANDRA_BROADCAST_ADDRESS=172.30.0.2
      - CASSANDRA_RPC_ADDRESS=172.30.0.2
      - CASSANDRA_SEEDS=172.30.0.2,172.30.0.3,172.30.0.4
      - CASSANDRA_NUM_TOKENS=128
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_CQL_PORT_NUMBER=9042
  cassandra2:
    image: cassandra:4.0.4
    hostname: cassandra2
    networks:
      cassandra-cluster:
        ipv4_address: 172.30.0.3
    expose:
      - 7000
      - 7001
      - 7199
      - 9043
      - 9142
    ports:
      - 9043:9043
    volumes:
      - cassandra2_data:/var/lib/cassandra
    environment:
      - CASSANDRA_LISTEN_ADDRESS=172.30.0.3
      - CASSANDRA_BROADCAST_ADDRESS=172.30.0.3
      - CASSANDRA_RPC_ADDRESS=172.30.0.3
      - CASSANDRA_SEEDS=172.30.0.2,172.30.0.3,172.30.0.4
      - CASSANDRA_NUM_TOKENS=128
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_CQL_PORT_NUMBER=9043
  cassandra3:
    image: cassandra:4.0.4
    hostname: cassandra3
    networks:
      cassandra-cluster:
        ipv4_address: 172.30.0.4
    expose:
      - 7000
      - 7001
      - 7199
      - 9044
      - 9142
    ports:
      - 9044:9044
    volumes:
      - cassandra3_data:/var/lib/cassandra
    environment:
      - CASSANDRA_LISTEN_ADDRESS=172.30.0.4
      - CASSANDRA_BROADCAST_ADDRESS=172.30.0.4
      - CASSANDRA_RPC_ADDRESS=172.30.0.4
      - CASSANDRA_SEEDS=172.30.0.2,172.30.0.3,172.30.0.4
      - CASSANDRA_NUM_TOKENS=128
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_CQL_PORT_NUMBER=9044
volumes:
  cassandra_data:
    driver: local
  cassandra2_data:
    driver: local
  cassandra3_data:
    driver: local
